var UserComponent = component('User');
var AuthComponent = component('Auth');
var BlankComponent = component('Auth');
var TenderComponent = component('Tender');
var VendorComponent = component('Vendor');
var MedicineComponent = component('Medicine');
var DemandComponent = component('Demand');
var ConfigsComponent = component('Configs');
var AttachmentComponent = component('Attachment');
var PreQualificationComponent = component('PreQualification');
var TechQualificationComponent = component('TechQualification');
var VendorprequaliComponent = component('Vendorprequali');
var VendortechqualiComponent = component('Vendortechquali');
var FinancialBiddingComponent = component('FinancialBidding');
var PurchaseOrderComponent = component('PurchaseOrder');
var GoodsRecievedComponent = component('GoodsRecieved');
var ContractTemplateComponent = component('Contracttemplate');
var VendorContractComponent = component('VendorContract');
var NavbarComponent = component('Navbar');
var BlacklistrequestComponent = component('Blacklistrequest');
var BlacklistvendorComponent = component('Blacklistvendor');
module.exports = function(router){
    AuthComponent(router);
    UserComponent(router);
    BlankComponent(router);
    TenderComponent(router);
    VendorComponent(router);
    MedicineComponent(router);
    DemandComponent(router);
    ConfigsComponent(router);
    AttachmentComponent(router);
    PreQualificationComponent(router);
    TechQualificationComponent(router);
    VendorprequaliComponent(router);
    VendortechqualiComponent(router);
    FinancialBiddingComponent(router);
    PurchaseOrderComponent(router);
    GoodsRecievedComponent(router);
    ContractTemplateComponent(router);
    VendorContractComponent(router);
    BlacklistrequestComponent(router);
    BlacklistvendorComponent(router);
    NavbarComponent(router);
}
